apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: postgresql
    meta.helm.sh/release-namespace: ortelius
  creationTimestamp: "2023-02-17T18:12:41Z"
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-12.2.0
  name: postgresql
  namespace: ortelius
  resourceVersion: "1860"
  uid: 2f3f13cc-537e-4e31-a1f0-7f342178421f
spec:
  clusterIP: 10.96.120.10
  clusterIPs:
  - 10.96.120.10
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-postgresql
    nodePort: 31432
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: postgresql
    app.kubernetes.io/name: postgresql
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
